#pragma once

/* Generated by asset converters. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
LV_IMAGE_DECLARE(image_cursor_hover);
LV_IMAGE_DECLARE(image_cursor_pressed);
LV_IMAGE_DECLARE(image_lock);

/* Fonts */
LV_FONT_DECLARE(font_noto_sans_sc_semibold_10);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_14);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_symbols_20);

#ifdef __cplusplus
}
#endif
